version: "2"

services:

  nginx:
    container_name: nginx
    restart: always
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/danny/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/danny/nginx/cert:/usr/local/nginx/cert:ro
      - /home/danny/nginx/conf.d:/etc/nginx/conf.d:ro
      - /home/danny/nginx/favicon.ico:/etc/nginx/html/favicon.ico:ro
      - /home/danny/nginx/log:/var/log/nginx
    environment:
      - TZ=Asia/Shanghai
    networks:
      macnet:
        ipv4_address: 172.16.2.1

  samba:
    container_name: samba
    restart: unless-stopped
    image: dperson/samba
    volumes:
      - /mnt/disk/Library:/Library
      - /mnt/drive/Library:/Store
    ports:  
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 445:445/tcp
    environment:
      - TZ=Asia/Shanghai
      - WORKGROUP=WORKGROUP
      - NMBD=True
    networks:
      macnet:
        ipv4_address: 172.16.2.2
    command:
      - "-u"
      - "danny;daniel;1000;staff;50"
      - "-s"
      - "library;/Library;yes;no;no;danny;danny;danny;library"
      - "-s"
      - "store;/Store;yes;no;no;danny;danny;danny;store"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Qixq@wDkdY!fB*GX@kMAD7cuJCadwmu2

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Qixq@wDkdY!fB*GX@kMAD7cuJCadwmu2

      
networks:
  macnet:
    external:
      name: macnet
